import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNavigation from "@/components/layout/MainNavigation";
import Banner from "@/components/layout/Banner";
import SessionProviders from "@/components/provider/Providers";
import UserContextProvider from "./context/UserContextProvider";
import ThProvider from "./ThemeProvider/ThProvider";
import NavigationApp from "./NavigationApp";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CYLegalChatBot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <UserContextProvider>
          <SessionProviders>
            <ThProvider>
              <MainNavigation />
              <NavigationApp children={children} />
              <Banner />
            </ThProvider>
          </SessionProviders>
        </UserContextProvider>
      </body>
    </html>
  );
}
